name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
      
    - name: Set Up MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '9.0'

    - name: Start MySQL
      run: |
        # sudo /etc/init.d/mysql start
        service mysql start

    - name: Test
      run: go test -v ./...