name: Run Tests with MySQL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: orm_golang_testing
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check MySQL connection status is ready
        run: |
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL connection status is ready..."
              break
            fi
            echo "Waiting for MySQL connection status reply.."
            sleep 2
          done

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        env:
          DB_MYSQL_HOST: 127.0.0.1
          DB_MYSQL_PORT: 3306
          DB_MYSQL_USER: root
          DB_MYSQL_PASS: password
          DB_MYSQL_DATABASE: orm_golang_testing
          DB_MYSQL_DATABASE_SSL: false
          DB_MYSQL_DATABASE_PROTOCOL: tcp
        run: |
          go test ./... -v -parallel=1
